### ISSUE TITLE
Spanish tree - strengthen link not working for grammar skills

### ISSUE THREAD

**Issue by immutability** [ToranSharma/Duo-Strength#113]
I think this is a follow-up to the fixes in issue #111 - the link for the new grammar skills that need strengthening does not seem to work and gets redirected back to the main page at (duolingo.com/learn).

I believe this may be because it lacks the /practice suffix? Right now my "Pres Tense 1" skill is marked and the link points to https://www.duolingo.com/skill/es/Pres-Tense-1 whereas regular skills seem to include the /practice at the end (after the skill name).

![duolingo_practice_link](https://user-images.githubusercontent.com/1141653/96547004-a14fc800-12ab-11eb-9797-eb6eefb0c9aa.png)

**Comment by ToranSharma** [comment]
Hi again,

Thanks for letting me know. I never checked the strengthening links as the tree I was testing on hadn't completed any of the grammar skills, so none needed strengthening.

The links should work for crown 1 grammar skills, but when they are golden, at level 2, I have not set it to add the /practice. It is still expecting to need to do this at level 5.

Should be an easy fix, though I won't be able to test it thoroughly.

Toran

**Comment by ToranSharma** [comment]
I have made the changes that should fix this issue in 24ca7b3.

As a related issue, I have also fixed the maximum crown count to account for this difference in grammar skills. That change is 02175a4.

**Comment by ToranSharma** [comment]
v1.3.36 has been published to all browsers with these fixes.

Thanks again,

Toran
