### ISSUE TITLE
CSS Selectors Need Update

### ISSUE THREAD

**Issue by mattfbacon** [ToranSharma/Duo-Strength#115]
It's that time again: `TypeError: Cannot read property 'getElementsByClassName' of null`

**Comment by ToranSharma** [comment]
Thanks for letting me know, I'll get a fix out as soon as possible.

**Comment by ToranSharma** [comment]
Luckily it wasn't too many things that had broken, it was just contained to the navigation bar and some of the elements in it.

I have updated the class names and selectors in 1e8e5ce.

This has been released as v1.3.37 and should now be available in all browsers.

**Comment by mattfbacon** [comment]
Thank you! Great work as always.
