### ISSUE TITLE
append is not a function

### ISSUE THREAD

**Issue by comproperty247** [ToranSharma/Duo-Strength#12]
Hi,

Got one small issue in your last version 1.0.14
"append is not a function"

Find this:

if(needToAddBox)
{
   topOfTree.append(strengthenBox);
}
with this:
if(needToAddBox)
{
   topOfTree.appendChild(strengthenBox);
}

Regards

**Comment by ToranSharma** [comment]
Hi,

Thanks for spotting this typo. Interestingly I don't get the error when that line of code is run, even though it should give the error you are getting.

Anyway this is been patched in c4f1c3cdd54dbf78bd5aadb70cfccb02f57a1a11 and will be pushed out in v1.0.15.

Thanks,

Toran

**Comment by comproperty247** [comment]
Hi,

Glad to help ;-)

I found out that in some cases, not sure when. All the console functions are 'blanked'
Sometimes I write console.log('something') and nothing return!! Is weird but true.

Yesterday I found this inside a another site! Explains what I am telling!!
Run this function bellow in your console and then try to write console.log('something'), will be empty!!
All methods in the array are made to show nothing!

Meanwhile I have one ideia for you to use in the new layout, but lets see if DL will have the new layout stable as I saw already some minor bugs.

Regards.

// Avoid `console` errors in browsers that lack a console.
(function () {
    var method;
    var noop = function noop() {};
    var methods = [
        'assert', 'clear', 'count', 'debug', 'dir', 'dirxml', 'error',
        'exception', 'group', 'groupCollapsed', 'groupEnd', 'info', 'log',
        'markTimeline', 'profile', 'profileEnd', 'table', 'time', 'timeEnd',
        'timeStamp', 'trace', 'warn'
    ];
    var length = methods.length;
    var console = (window.console = window.console || {});
    while (length--) {
        method = methods[length];
        // Only stub undefined methods.
        if (!console[method]) {
            console[method] = noop;
        }
    }
}());
