### ISSUE TITLE
Tips pages - add start lesson & practice buttons to the boom of the page

### ISSUE THREAD

**Issue by alexseyk** [ToranSharma/Duo-Strength#122]
In some language courses there are pages with tips (theory) ex: https://www.duolingo.com/skill/es/**SkillName**/tips. They have a "Start Lesson" button in the top right corner of the page. Can you add or duplicate such button to the bottom of the corresponding tips page ? and may be add "Pratctise" button too. Thanks.

**Comment by ToranSharma** [comment]
Sure, I have had a similar thought before when on a tips page. I'll look into it.

**Comment by ToranSharma** [comment]
I have split this features into two options. One to add the practise button next to the start lesson button. And a second to repeat all the buttons at the top of the page, at the bottom.

![image](https://user-images.githubusercontent.com/4559968/103929733-a0de0500-5115-11eb-8668-c63af788fc7f.png)
... and at the bottom
![image](https://user-images.githubusercontent.com/4559968/103929784-b5ba9880-5115-11eb-9672-f4c93ec6e241.png)


Note it handles the start lesson button already being a practise button for L5 skills, L2 Grammar skills and L1 bonus skills (not that I think any have tips pages but just in case).

This change was added into the develop branch in 4c34293.
