### ISSUE TITLE
re-do checkpoint challenge button 

### ISSUE THREAD

**Issue by alexseyk** [ToranSharma/Duo-Strength#123]
Please bring back the button to re-do checkpoint challenge. 
https://www.duolingo.com/checkpoint/LanguageCode/Number/
Note that content is different from the practice mode i.e. 
https://www.duolingo.com/checkpoint/LanguageCode/Number/practice.

**Comment by ToranSharma** [comment]
Sure, I didn't realise that it was different when I stopped adding that button on checkpoints with the "PRACTICE +10 XP" button.

It has been added back in 4859682.

I will release this as v1.3.40 shortly.
