### ISSUE TITLE
total strength and breakdown 

### ISSUE THREAD

**Issue by alexseyk** [ToranSharma/Duo-Strength#125]
Can you add total strength and breakdown akin to duome ? 

<img width="313" alt="Screen Shot 2020-11-27 at 11 32 25" src="https://user-images.githubusercontent.com/60418150/100411498-84759400-30a4-11eb-9d8e-7ea55f17c170.png">

Possibly as a side bar and/or part of the Need Strengthening message

**Comment by ToranSharma** [comment]
Hi, I am looking at add this now. The breakdown and the total strength don't seem to add up in general.

I would assume that the total strength is the average strength of all the skills, not including skills that you haven't started (0% strength). For your example would give:
```(10*1.0 + 8*.075 + 8*0.5 + 53*0.25) / (10 + 8 + 8 + 53) = 0.421 = 42.1%```
Which is pretty much what duome shows.

However if you take my en->es:
![image](https://user-images.githubusercontent.com/4559968/103682882-5cb9fb80-4f81-11eb-86b0-5e16ae6b4783.png)
```(65*1.0 + 1*0.75 + 1* 0.5) / (65 + 1 + 1) = 0.989 = 98.9%```
But duome shows 96%.

This 96% seems to come from duolingo itself in the user's extended profile, in Duo Strength this would be accessed by:
```userData.language_data.es.language_strength``` for a spanish tree.

This gives the 96% that duome shows. I cannot understand however where this is coming from.

I thought that maybe it isn't including skills that you haven't finished yet, i.e. all crown 0 skills. But this gives a slightly higher value still.

What would you prefer to see, the duolingo version or the manually calculated version?

**Comment by ToranSharma** [comment]
Here is what it looks like currently using the averaged strengths of the non crown 0 skills:

![image](https://user-images.githubusercontent.com/4559968/103692066-27b4a580-4f8f-11eb-9c2a-e549f81047a4.png)

**Comment by ToranSharma** [comment]
Note bonus skills not included in any stage of this. Duome also doesn't seem to include them in the breakdown.

**Comment by ToranSharma** [comment]
The only thing I can think of is that it is an average of the strengths of all the words that a user has learnt. I don't have a good way of checking that however.

**Comment by alexseyk** [comment]
Manual calculation makes more sense to me.

**Comment by ToranSharma** [comment]
Okay, I'll keep that then.

I have changed it to not show strength values with have zero skills. Here is how the final box will look:

![image](https://user-images.githubusercontent.com/4559968/103915392-112f5b00-5103-11eb-83f7-51c892aca3d3.png)


This feature has been added to the development branch in 7983b6e.
