### ISSUE TITLE
Tree level prediction algorithm 

### ISSUE THREAD

**Issue by alexseyk** [ToranSharma/Duo-Strength#126]
It is strange that raising  skills to +1 crown level counts towards achieving next tree Level.

Example: My tree is at L2.  and was predicted to be at L3 in 2021. I have some skills at L3 which i raised to L4. Now it predicts i will reach L3 by the end of 2020.

Personally i would use only skills  that were raised from L2 to L3 as prediction to achieving L3 tree.

**Comment by ToranSharma** [comment]
It should already be working as you suggest. There are a few things that could cause the prediction date to change. The first is that that you are seeing a fall-back prediction method being used. The second is that it is using the main prediction algorithm, and you noticed the date change when you reached your daily goal, which is when it takes into account the progress you have made today.

There are two prediction methods: one based off of the user's extended profile file, and one based off of Duo Strengths saved record of the changing progress over time. The latter can only be used if there is enough saved data, it requires at least 5 progress making entries (essentially 5 days on which progress was made towards the next tree level). If there is not enough of these entries, the first method based off of the calendar section of the user's data file. This calendar method is (as far as I can tell) what duome uses.

The calendar section in the userData file is a record of all the XP earning events of a user from the last 3 weeks, with how much XP was earned, the skill ID (if not a story) and a timestamp of when it happened. This is the same information that you view if you click on show RAW on duome above the daily progress graph. Here is a sample of my calendar:

```javascript
7:  {skill_id: "c37fb34b037212ed2332436bdfb83253", improvement: 12, event_type: "lesson", datetime: 1605559780000}
8:  {skill_id: "fb9af227309b0ab90d81c5e1caedfe5d", improvement: 14, event_type: "lesson", datetime: 1605560155000}
9:  {skill_id: "a15377a46caf42e948441cf0f3777376", improvement: 10, event_type: "practice", datetime: 1605653674000}
10: {skill_id: "c7fdf4e20d652becf3da33b2cb394f0d", improvement: 12, event_type: "lesson", datetime: 1605654010000}
11: {skill_id: null, improvement: 18, event_type: "practice", datetime: 1605654178000}
12: {skill_id: "30417892911333802be5f2daba516e24", improvement: 10, event_type: "practice", datetime: 1605740995000}
13: {skill_id: "7210bee5a1de77d558c1dc561be73260", improvement: 10, event_type: "practice", datetime: 1605741180000}
```

This data is filtered based on the skill_id to make sure that it ignores any skills that are not for the current tree. You can see that there is no way of knowing from this data alone what crown level the skill was at, so all lessons are counted in the prediction method. This means that this method tends to over estimate the progress rate and so puts the date too soon.

If this method is being used, then it could have the effect you describe where doing a lesson that shouldn't contribute towards getting you to the next tree level, changes the predicted date.

The second method, based on the saved progress history should be more accurate, as it will only look at lessons that contribute towards getting to the next tree level, just as you suggest. This method works by saving an entry for each day that any progress is made towards getting to the next level. I.e. it looks at the total number of lessons left on skills that are at the current tree level, and records how much this changes every day. You have seen this record before, but here is a sample of mine:
```javascript
67: (3) [1604275200000, 0, 468]
68: (3) [1604361600000, 0, 467]
69: (3) [1604880000000, 0, 466]
70: (3) [1605657600000, 0, 465]
71: (3) [1606089600000, 0, 463]
72: (3) [1606521600000, 0, 462]
```
The first entry is the timestamp of midnight of that day, the second is the tree level at the time, and the last is the number of lessons remaining to go until the next tree level. The 7 most recent entries from this information is used to calculate the average number of lessons done per day that contribute to getting to the next tree level, and that is then used to work out how long it will be until the user gets there.

Also note that the progress graph in the crowns info is just displaying this information but showing the change between entries for each day of the last week. Here only the last two entries in the above are from the last week and are shown in the graph below:
![image](https://user-images.githubusercontent.com/4559968/100549132-10381d80-3269-11eb-8e6a-9017b40174f0.png)

An entry from the current day is only used as part of the prediction algorithm if the user has met their daily goal for today. This is to avoid the date fluctuating while the user is doing their lessons for the day. For example, suppose that the user typically does 3 lessons per day that contribute towards getting to the next tree level. At the start of any given day, after the first lesson has been completed, if today's progress is included in the prediction algorithm, it will stand out compared to the previous days as there has only been one progress making lesson done, and thus push down the average progress rate, making the predicted level up date further into the future. To stop this, the current day's entry is not included until the daily goal is met, at which point it is supposed that it is representative enough to include.

I hope that helps explain what could be going on. Of course there could also be a bug in the saving of the progress entries, but from my end nothing looks out of place.

**Comment by alexseyk** [comment]
wow, such a lengthy answer to my humble comment!  What did i do to  merit such detail technical explanation :) 

FYI  I observed  change in date prediction after i achieve my daily goal 
** Is there a way to check which prediction method is used ?**

I've been working on spanish tree for 2+weeks. So there should be plenty of data for DuoStrength to use 
Do you use local midnight  or ~~San Francisco~~  GMT0 as in leagues ?

To check for space I run as in  https://github.com/ToranSharma/Duo-Strength/issues/117#issuecomment-718763047
and my result is : 
There are 1930B/102400B being used in total
There are 692B/8192B being used in a single entry for the progress history

Yes i can see on the graph that none of the lessons recently done contribute to the next tree Level. (normally i have that graph turned off)

However when i focus on the **current rate** and estimated days till completion - they changed during the day!
Today i only raised strength back to 100% on a number of L2 skills. 

Note that rate  & days changed from 9.50 & 31 to 10.42 & 28 days ( which makes NO sense) 
Prediction  @ Duome changed  from 15.89 & 18 to 15.66 & 19 days ( which makes sense) 

So it's not crowns but lessons completed in a day. IMHO as none of the lessons done during the day count towards next tree Level they should not be used in the prediction. 

I guess that means that 1st method of prediction was used ( based on Duome data) 
Below are screenshots:  1.at the start and 2.at the end of the day 

<img width="1358" alt="9 50 - 286" src="https://user-images.githubusercontent.com/60418150/100616570-dd1a8a80-334b-11eb-80ed-310b8c3cb5d7.png">

<img width="1041" alt="10 42" src="https://user-images.githubusercontent.com/60418150/100617955-c37a4280-334d-11eb-9f11-10b531f81dab.png">

**Comment by ToranSharma** [comment]
I am happy to explain the workings of things! It helps me make sure I fully have my head around what I am doing.

> FYI I observed change in date prediction after i achieve my daily goal
> ** Is there a way to check which prediction method is used ?**

Looking at the code, both prediction methods should only update after the daily goal has been reached for the reason mentioned previously.

You can see which prediction algorithm you are using just by running the two different prediction methods:
```javascript
daysToNextTreeLevel()
daysToNextTreeLevelByCalendar()
```
Then see which one corresponds to what is being shown in the crowns info. Both functions return an object, with a time (in days), a rate (in lessons/day) and the number of lessons left to complete.

You can also run 
```javascript
progress.length
```
to see if it is over the needed 5 data points to use the non calendar method. This match the results of the above.

> Note that rate & days changed from 9.50 & 31 to 10.42 & 28 days ( which makes NO sense)
> Prediction @ Duome changed from 15.89 & 18 to 15.66 & 19 days ( which makes sense)

I will have to see what duome is doing if there are some discrepancies between the calendar method and duome's prediction. In theory they can also do a bit better than the calendar method as they have a record of the crown level of each skill so can work out (to some degree of accuracy) if a lesson contributed to getting to the next tree level or not.

> So it's not crowns but lessons completed in a day. IMHO as none of the lessons done during the day count towards next tree Level they should not be used in the prediction.

Yes, the progress based method counts lessons that reduce the total number left to get to the next tree level. It doesn't matter if they happen to be the last lesson of skill that actually earns to crown. All lessons on skills of the correct crown level will contribute towards to prediction.

> Do you use local midnight or San Francisco GMT0 as in leagues ?
The timestamps in the progress history list, should be for midnight local time.

> To check for space I run as in #117 (comment)
> and my result is :
> There are 1930B/102400B being used in total
> There are 692B/8192B being used in a single entry for the progress history

Should be no issues currently. I still need to address the filling up of data found in #117, I will try to get to it in the next couple of days.

**Comment by alexseyk** [comment]
progress.length said **4**
I am puzzled. I'll keep an eye on it.

**Comment by alexseyk** [comment]
Obviously re-installing your plug-in or changing my user name (?)will reset the progress day counter. I just don't remember doing it... 
Other possible causes are
Chrome update
Joining a classroom 
Achieving daily goal on a different language course
Achieving daily goal on a different device 
Achieving daily goal in  a different browser
Starting with (and or doing only) practice(dumbbells)
Starting with (and or doing only) stories

**Comment by alexseyk** [comment]
Now that progress.length says 6 prediction works properly :)
