### ISSUE TITLE
Disappeared: Retry & Test Out Buttons on Completed Checkpoints

### ISSUE THREAD

**Issue by alexseyk** [ToranSharma/Duo-Strength#130]
Retry & Test Out Buttons on Completed Checkpoints are not shown any more. Except on the last one ( golden owl) and even on the owl the button  "Retry checkpoint challenge"  directs to practice  not to original challenge. Duolingo has "practice" buttons  only on checkpoints and not on the owl. Pls consider adding.

**Comment by ToranSharma** [comment]
I can see the checkpoint retry challenge and test out buttons are missing. I will look into it and get a fix out as when I can.

I will also add a third practise button to the final golden owl button that matches the duolingo button on the rest of the checkpoints. I am not sure if you will earn the +10 XP for that checkpoint or not.

**Comment by ToranSharma** [comment]
The checkpoint buttons have been fixed in 693e35f.

A PRACTICE +10 XP button has been added to the final checkpoint (golden owl message) in 71687a5. The Retry Checkpoint Challenge button has also been fixed in this change to point to the challenge and not the practice.

**Comment by ToranSharma** [comment]
v1.3.43 has been published with these changes
