### ISSUE TITLE
Colored Flag Border stopped working v2.0

### ISSUE THREAD

**Issue by alexseyk** [ToranSharma/Duo-Strength#144]
Colored Flag Border does not work on Chrome, Reinstalling extension did not help . It seems that border is displayed with transparent or white color. 
<img width="319" alt="Screen Shot 2021-03-02 at 11 28 22" src="https://user-images.githubusercontent.com/60418150/109597226-69ef0300-7b4a-11eb-82ff-1159298a9afb.png">

**Comment by ToranSharma** [comment]
Found the issue, was just a small mistake that meant the tree level storing function exited too early.

Fixed in 02527f6. Will be part of v2.0.1

**Comment by ToranSharma** [comment]
Let me know after the update if the flags are still misaligned as that is a separate matter.

**Comment by ToranSharma** [comment]
NB v2.0.1 has been released
