### ISSUE TITLE
Hide cartoons & audio buttons border

### ISSUE THREAD

**Issue by alexseyk** [ToranSharma/Duo-Strength#145]
Enabling hide cartoons removes border from the audio buttons :( 
<img width="680" alt="Screen Shot 2021-03-02 at 11 29 33" src="https://user-images.githubusercontent.com/60418150/109598103-2f399a80-7b4b-11eb-8c1a-fc42c45ee754.png">

<img width="722" alt="Screen Shot 2021-03-02 at 11 29 50" src="https://user-images.githubusercontent.com/60418150/109598131-424c6a80-7b4b-11eb-8f2a-fe00436d5ea8.png">

PS Duolingo has inhouse disable animations in settings... it used to just disabled animations and  not also hide cartoon

**Comment by ToranSharma** [comment]
The lack of border around the audio buttons looks fine to my eyes. The middle border is the important one for dividing the buttons and that is still there.


Not sure what is going on with the second screenshot. Can you explain more what you are showing there? It looks like the cartoon is being removed be something else.

**Comment by alexseyk** [comment]
The 2nd screenshot was to show the contrast. I have cartoons hidden with ad block rule  duolingo.com##._1RL1c

**Comment by ToranSharma** [comment]
I have added a new option to keep the border when hiding the cartoon:
![keep-question-borders](https://user-images.githubusercontent.com/4559968/109683053-e3044f80-7b76-11eb-9903-7b315c7fd1f4.png)
before
![without-border](https://user-images.githubusercontent.com/4559968/109683063-e5ff4000-7b76-11eb-94eb-bb04e6c48809.png)
after
![with-border](https://user-images.githubusercontent.com/4559968/109683061-e566a980-7b76-11eb-9fe3-33593fd34b5f.png)


before
![without-border2](https://user-images.githubusercontent.com/4559968/109683388-34acda00-7b77-11eb-83a5-0a9e6edd0ae3.png)
after
![with-border2](https://user-images.githubusercontent.com/4559968/109683386-34144380-7b77-11eb-9dad-b4dcf68ec705.png)

**Comment by ToranSharma** [comment]
I removed the speech bubble arrow from the left so they are just borders now I suppose. I will change the option name to reflect that.

**Comment by ToranSharma** [comment]
Added in c336552.
