### ISSUE TITLE
Focus mode & Shop & Settings & Profile pages 

### ISSUE THREAD

**Issue by alexseyk** [ToranSharma/Duo-Strength#146]
Enabling Focus mode, hides the sider bar at  the shop page. Please add button to show/hide sidebar at the Shop page or do not hide side bar at the Shop page in the Focus Mode 

Same for the Settings page i.e. https://www.duolingo.com/settings/account  :(

**Comment by ToranSharma** [comment]
I didn't know about this but it must have slipped through the net in testing

**Comment by alexseyk** [comment]
I've seen such behavior when i tried to block some  side bar window  as a class. and then discovered certain items missing at the settings page :(

**Comment by ToranSharma** [comment]
I have added a check before applying the focus mode to see if the user is on the learn page or not.

Should be fixed in a8fcf43 and 702888b. The tips page will still have the side bar hidden, but shop and profile pages will not.

Will be released as part of v2.0.1
