### ISSUE TITLE
Practice Crown 0 Skills on Bonus Skills is ignored

### ISSUE THREAD

**Issue by alexseyk** [ToranSharma/Duo-Strength#147]
At  the Bonus skills (spanish) practice @ 0 crown level is ignored and works towards earning more crowns. Works fine on other skills :)

**Comment by ToranSharma** [comment]
Do you mean this option?
![L0-practise-button](https://user-images.githubusercontent.com/4559968/109663811-69636600-7b64-11eb-9e73-2083ef630dcd.png)


As that seems to be working fine for me.

Alternatively are you trying to set the practise threshold setting to 0:
![practise-threshold](https://user-images.githubusercontent.com/4559968/109665025-ac720900-7b65-11eb-8ae1-0e1f56ddbd3f.png)
If so, this setting is limited to 1 being the lowest, as otherwise what you want is to set "Link Session Type" to "Practice (Strengthen Only)"

Note that this setting only affect links in lists and not the buttons in the skill popout bubbles

**Comment by alexseyk** [comment]
Yes, that option. 
No My  Practice threshold is set to 4 and besides My link session type  is set to Practice (Strength Only)
Ok, So i reseted Spanish  tree and tried again with bonus skills 
and crown level was increased, by just doing practice 

This issue affect only bonus skills... may have to do practice twice to see the effect.

**Comment by ToranSharma** [comment]
Okay, and you are clicking the "PRACTISE" button not the "START LESSON" button:
![image](https://user-images.githubusercontent.com/4559968/109675456-b993f580-7b6f-11eb-9c09-dd84dbd0e35e.png)

For me the "PRACTISE" button points to https://www.duolingo.com/skill/es/Idioms-and-Proverbs/practice compared to https://www.duolingo.com/skill/es/Idioms-and-Proverbs/2 if I click the "START LESSON" button.

I will try doing a practise the see if it progresses me.

**Comment by ToranSharma** [comment]
Just did a practice and got 10XP, the state of the skill is unchanged in the number of lessons remaing

![image](https://user-images.githubusercontent.com/4559968/109676539-b5b4a300-7b70-11eb-9afe-951287bcc7a4.png)

**Comment by ToranSharma** [comment]
Just did another and got 10XP with practice in the URL and it got me up to crown 1. I have no idea what is going on here

**Comment by ToranSharma** [comment]
Practice really isn't designed for L0 skills. There could be an issue on duolingos ends that doesn't handle it very well. I will try several times on a non bonus skill to see if I can get the same thing to happen there.

**Comment by alexseyk** [comment]
I am glad that you are able to reproduce the issue. The easiest thing is just to ignore / exclude  the bonus skills ( do  not add practice button when they are at Level 0) . They might be phasing out as i don't see them on  a new account on  nuevo  arbol de ingles

**Comment by ToranSharma** [comment]
Yeah, I think you are right, a user with an updated german tree reported issues around bonus skills that I coulnd't repoduce but managed to fix. They mentioned that the bonus skills were being removed from tree updates.

**Comment by alexseyk** [comment]
> Practice really isn't designed for L0 skills.

I agree :) But i guess someone asked for such option.    

When i do global practice or practice on a tower (castle) it uses sentences only from the open skills...

**Comment by ToranSharma** [comment]
Just tried practising a L0 normal skill that I hadn't started yet. Got 10XP first time, no change to number of lessons shown or in the user data file. Did a second practice and got 0XP saying that skill was out of XP for the day come back tomorrow. This is not what happened to the bonus skill, I got 10XP both times. Something must be wrong with just bonus skills.

454caf9 removes the button from L0 bonus skills.
