### ISSUE TITLE
Total Strength UI suggestion

### ISSUE THREAD

**Issue by alexseyk** [ToranSharma/Duo-Strength#148]
Is it possible to put Total Strength side bar above the Leagues & Daily XP sidebars ?  and / or add it to the Lingots popup

**Comment by ToranSharma** [comment]
I suppose I could make a option to customise the order all the sidebar boxes.

An option to add it to the lingots popup or similar is also possible.

**Comment by ToranSharma** [comment]
339d1ab 37c33d5 Add a new multi part option to pick the ordering of the sidebar boxes.

You sort it to whatever degree you like, any items not sorted will be left in their default order before the option was applied. Namely this is:

"leagues", "XPBox", "languagesBox", "totalStrengthBox", "crownsBox", "ad", "achievementBox", "friendsBox", "socialButtonsBox"

Here is how it looks:
![sidebar-box-order](https://user-images.githubusercontent.com/4559968/109723335-de0ac480-7ba5-11eb-9cd0-e176eb69eca6.png)

I hope this works for you. I think doesn't quite fit in any of the popups really, it has nothing to do with lingots, crowns or your streak.
