### ISSUE TITLE
UI: Mastery & TestOut buttons

### ISSUE THREAD

**Issue by alexseyk** [ToranSharma/Duo-Strength#153]
Adding Mastered Skill button changes size / shape of the Test out button  aka "key" 
<img width="427" alt="Screen Shot 2021-03-03 at 07 52 30" src="https://user-images.githubusercontent.com/60418150/109735878-0a4e3180-7bf6-11eb-9ecc-8a856226f7a8.png">
<img width="418" alt="Screen Shot 2021-03-03 at 07 52 47" src="https://user-images.githubusercontent.com/60418150/109735880-0cb08b80-7bf6-11eb-8a70-094d33fb3832.png">

PS Words button has the same effect on the "key"

**Comment by ToranSharma** [comment]
I though that it was a necessary consequence of having the extra buttons but have managed to work it out with new styling
![image](https://user-images.githubusercontent.com/4559968/109811178-6464ec00-7c22-11eb-91fa-dda26fe51568.png)
![image](https://user-images.githubusercontent.com/4559968/109811329-94ac8a80-7c22-11eb-81dc-9a0ec8f6d4d9.png)
![image](https://user-images.githubusercontent.com/4559968/109811502-d3424500-7c22-11eb-993d-f21e8881a7ca.png)
![image](https://user-images.githubusercontent.com/4559968/109811439-bdcd1b00-7c22-11eb-85a4-0488d19809c1.png)

Changed in 126ea4f
