### ISSUE TITLE
Bug Update 2.01 Breaks on Chrome

### ISSUE THREAD

**Issue by georgeawg** [ToranSharma/Duo-Strength#155]
Update 2.01 updates breaks DuoStrength for me

> Uncaught SyntaxError: Unexpected token . At chrome-extension://oghbejipobmlmgfbdjmfgnnhepngcmle/duoStrength.js:489> > > Uncaught SyntaxError: Unexpected token .

Nothing gets added to the page; No strength bars, no lists of broken skills, no lists of skills that need strengthening, nothing.

Is there a way to revert to the old version??

https://forum.duolingo.com/comment/47298041?comment_id=47332672

**Comment by ToranSharma** [comment]
Just replied to this comment on the forum:

Sorry about that. I'll look into to. I don't know of an easy way to back date on Chrome. I think you can find old versions on the Firefox store page somewhere, don't know about opera.

**Comment by ToranSharma** [comment]
Which browser are you using? The line your error is pointing to looks fine to me, it is however using a javascript operator that maybe has poor support in older versions of Edge.

**Comment by ToranSharma** [comment]
Sorry just seen that you are using Chrome in your title. Can I ask which version. The line your issue points to would only give that error on versions before Chrome v80

**Comment by ToranSharma** [comment]
I have removed all uses of the optional chaining operator (?.) and nullish coalescing operator (??) in 056c69de97798f3b24f7b1a5407302cbe540ad0c and the use of named RegExp groups in 5ca9e958c27d622b925917a67b34a54bc990f7a6. These javascript features were added in 2020 browser versions.

These fixes will be included as part of v2.0.2.

Please consider updating your browser for security and compatibility reasons if your system allows.

**Comment by georgeawg** [comment]
Thanks, the problem is now fixed.

I can't update my browser because it is a Samsung XE303 Chromebook which is no longer being updated by Google. I am stuck with legacy ChromeOS 75 for my both my Chromebooks.

I am glad that I don't have to buy a new computer to use your extension. The feature that obscures the words is awesome and has been a great help to me. It is such a pleasure to click the "check" button and see that I heard the question correctly.

Thanks again.
