### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by Origitalus** [ToranSharma/Duo-Strength#166]
Yesterday everything was fine, now nothing works, as if the addon is disabled.
I have Firefox 87.0 (64-bit)
I already restarted Browser and disabled and reenabled the addon.

**Comment by ToranSharma** [comment]
What version are you on? V2.0.3 was released yesterday to account for a change on Duolingo's end. If you are on v2.0.3 and it isn't working then maybe the Duolingo changes weren't rolled out to all users.

**Comment by Origitalus** [comment]
Ah, I did manual update to 2.0.3 and it works, thanks!
