### ISSUE TITLE
SIDEBAR BOX SORT ORDER  & Plus Progress Quiz 

### ISSUE THREAD

**Issue by alexseyk** [ToranSharma/Duo-Strength#167]
Progress Quiz from Plus package is not available for SIDEBAR BOX SORT ORDER
please add 

FYI:  DL is having  a campaign : invite  friends - get plus. 
<img width="908" alt="Screen Shot 2021-04-02 at 22 13 51" src="https://user-images.githubusercontent.com/60418150/113428295-c02cbb80-9400-11eb-81c9-45ba077c9566.png">

**Comment by ToranSharma** [comment]
I will add that to the boxes that can be sorted. Thanks for the screenshot with the class names in, that really helps.

**Comment by alexseyk** [comment]
Here is another table to add to the list :)
<img width="865" alt="Screen Shot 2021-04-03 at 22 52 34" src="https://user-images.githubusercontent.com/60418150/113483884-cccc1500-94cf-11eb-9a42-b350523026c7.png">

**Comment by ToranSharma** [comment]
Added sorting options for these in ace15c5.

Can't test it myself, so let me know if there are any issues.
