### ISSUE TITLE
UI: Crowns - bold font 

### ISSUE THREAD

**Issue by alexseyk** [ToranSharma/Duo-Strength#169]
May be use bold font for the "Your tree is at level X " ? 
<img width="357" alt="Screen Shot 2021-04-05 at 11 17 01" src="https://user-images.githubusercontent.com/60418150/113536550-93df8d80-9600-11eb-8e3d-5bb165f02b11.png">

**Comment by ToranSharma** [comment]
Changed in f7b4a2b.
