### ISSUE TITLE
Cracked Skills List, Word Button, Needs Strengthening List gone.

### ISSUE THREAD

**Issue by Origitalus** [ToranSharma/Duo-Strength#176]
Hi,

since today I am missing my beloved Cracked Skills List and Word Button. Needs Strengthening List is also missing.
Firefox 90.0.2 (64-bit)

It's probably unrelated but I recently got the "You finished #1 in your leaderboard" achievement and reached 60000 XP.
And right now I am on the last place in my league.

**Comment by ToranSharma** [comment]
Hi,

Can I ask which Duo Strength version you are using. I published a fix today of someone reporting a very similar issue.

The version with the fix is v2.0.8.

Toran

**Comment by Origitalus** [comment]
Ah okay, I had old version. It works now, thanks
