### ISSUE TITLE
Words button and Needs Strengthening List disappear 

### ISSUE THREAD

**Issue by Origitalus** [ToranSharma/Duo-Strength#177]
Bug since last patch: Words button and Needs Strengthening List disappear after I practice a non-cracked lesson.
But all is back to normal after I press F5
EDIT: Same with cracked lessons

**Comment by ToranSharma** [comment]
Thanks for reporting this, I'll look into it when I can.

**Comment by ToranSharma** [comment]
I have fixed this issue in v2.0.9 which I will publish shortly.

Thanks for the report.

**Comment by Origitalus** [comment]
Same thing again since a week or so.

**Comment by ToranSharma** [comment]
Thanks for letting me know. I'll try to sort it asap.

**Comment by ToranSharma** [comment]
I have just released v2.0.12 which should fix this. It will be pushed out to users in the next few hours.

Let me know if any more issues,

Toran
