### ISSUE TITLE
Checkpoint NaN

### ISSUE THREAD

**Issue by enrico3** [ToranSharma/Duo-Strength#184]
The info at the top tells me that I need to complete 'Checkpoint NaN':
![image](https://user-images.githubusercontent.com/31779179/134638852-b322cd4c-5136-42e4-87b7-f30e31939958.png)

The link points to https://www.duolingo.com/checkpoint/ru/undefined/

**Comment by ToranSharma** [comment]
Thanks for the report I'll look into it now. Can you confirm this is using the latest version 2.0.13?

**Comment by enrico3** [comment]
Yes, I have version 2.0.13

**Comment by ToranSharma** [comment]
Thanks, I have managed to reproduce and find the issue. This has been fixed in 4d5fae2.

I will release v2.0.14 with this fix shortly. Thanks again for the report.

Toran
