### ISSUE TITLE
SideBar box Sort order - new item

### ISSUE THREAD

**Issue by alexseyk** [ToranSharma/Duo-Strength#191]
please add "my assignments" to the sort order.
It is available when a user joins a classroom in school i.e. "shares progress"
<img width="842" alt="Screen Shot 2021-10-01 at 11 46 12" src="https://user-images.githubusercontent.com/60418150/135566679-10ff1dc9-018a-4399-8f9e-1b4979818d8c.png">

**Comment by ToranSharma** [comment]
Thanks for the report, can you tell me where the box goes with the extension disabled?

This screenshot I found on Google images shows it just below the XP box, but I think it is probably fairly old
![image](https://user-images.githubusercontent.com/4559968/135660574-71507ce1-06ed-49b5-b0d3-8c8679a9286b.png)

**Comment by ToranSharma** [comment]
I have added the handling for box this in 0a0497e. Currently I have placed it in the unsorted order just before the Progress Quiz box. Let me know if this is incorrect and I will move it to the proper place.

**Comment by alexseyk** [comment]
FYI with disabled extension it shows at the top... above leagues

**Comment by ToranSharma** [comment]
Fixed in v2.0.18
