### ISSUE TITLE
Error with skillElements[i].childNodes[0].getElementsByTagName(...)[Symbol.iterator] is not a function(…)

### ISSUE THREAD

**Issue by comproperty247** [ToranSharma/Duo-Strength#2]
replace line 62 in duoStrength.js  with this one and will work 

for (var spanElement of Array.from(skillElements[i].childNodes[0].getElementsByTagName('span')) )

Regards

**Comment by ToranSharma** [comment]
Thanks for the suggestion. I haven't seen this error but it seems like it might be browser specific, or browser version dependent. Change made in commit 0f27157. I'll push out a new version shortly.

**Comment by ToranSharma** [comment]
Update v1.0.5 has been pushed out.

Thanks for your help,

Toran

**Comment by comproperty247** [comment]
Glad to help.
I will push your new version and send feedback if necessary.

Regards,
Carlos
