### ISSUE TITLE
Remove lingo cost from legendary button  - misunderstanding \ wording 

### ISSUE THREAD

**Issue by alexseyk** [ToranSharma/Duo-Strength#202]
Hi 

The way this option behaved i suggest you rename it to "auto charge ingot cost"  or "skip cost page " or " bypass cosrt / price warning page "  or similar unless i misunderstood how it should work.

I was expecting it will cost me 0 ingots but instead it charged ingots without warning me

**Comment by ToranSharma** [comment]
I didn't realise I left that in anywhere. When I was first testing the
legendary stuff, it appeared as if it was not taking the lingot cost, but I
realised that it just doesn't ask but takes it anyway so I removed it. Or
so I thought!

I'll just remove the option and it doesn't do anything as far as remember,
all the script side stuff was removed.

Thanks for spotting this.

**Comment by ToranSharma** [comment]
Removed in 3d6e3c7
