### ISSUE TITLE
Sentence hiding doesn't work

### ISSUE THREAD

**Issue by Origitalus** [ToranSharma/Duo-Strength#205]
Sentence hiding doesn't work since a couple days or so.

![image](https://user-images.githubusercontent.com/60040210/145116498-291f576c-6056-4eec-b42a-a178d8cb2767.png)

**Comment by ToranSharma** [comment]
Thanks for reporting. I'll have a look as soon as I can.

**Comment by ToranSharma** [comment]
I have fixed this in 85cfa75. I will release v2.0.22 shortly with this fix.
