### ISSUE TITLE
Bug: Automatic scroll to bottom and back after finishing a lesson. 

### ISSUE THREAD

**Issue by Origitalus** [ToranSharma/Duo-Strength#210]
Severity: annoying.

Hey, 
this started after a reinstallation of Firefox, so I guess it must be some setting, which I cant figure out.
After I finish a lesson, the screen is focused on that lesson for half a second. Then I get scrolled down to the bottom and stays there for a few seconds, before it scrolls back up to focus on the finished lesson.

**Comment by Origitalus** [comment]
I noticed that it doesnt scroll completely to the bottom, just pages down or so.

**Comment by Origitalus** [comment]
Thank's for fixing!

**Comment by Origitalus** [comment]
Hm its back again :( 
So confused.

**Comment by ToranSharma** [comment]
Hi @Origitalus, sorry for never responding to your issue. Possibly the setting that is causing this is one called 'Focus First Skill in List' try unchecking that and see if it helps. This option is fairly near the top of the list. I would provide a screenshot but I am replying on my phone.

**Comment by Origitalus** [comment]
That's not it, it has been unchecked for a long time. 
The issue was gone in the last couple days and now its back, and I didnt change anything.
Weeiird.

**Comment by ToranSharma** [comment]
@Origitalus I think I have fixed the issue you mentioned.
Let me know if v2.0.28 which I am about to release sorts it out and I will close this.

Sorry for the long delay in looking into this.

**Comment by Origitalus** [comment]
Yes it works, thanks a lot!
