### ISSUE TITLE
DuoStrength not working after recent Duolingo update

### ISSUE THREAD

**Issue by Ajakab98** [ToranSharma/Duo-Strength#222]
Hey ToranSharma,

Thank you for making and updating the DuoStrength extension, I really like it, especially the sentence hiding and the word list feature!

I saw that the desktop version of Duolingo changed quite recently, about week ago. Most notably the layout changed so that sections are on the top left, as seen in the screenshot below:
![image](https://user-images.githubusercontent.com/112017036/195194900-f542732a-daaa-41bb-9c9b-b174bd713b3c.png)

Soon after this change appeared for me on my desktop (using Microsoft Edge browser), the DuoStrength extension stopped working, as I couldn't see any of its features appearing.

I tried reinstalling the extension, and I also tried using Brave browser and reinstalling it on there too, but nothing makes the DuoStrength features come back as of currently.

Please let us know if it would be possible to update the extension so it works along with the redesigned desktop Duolingo.

Thanks in advance,
a DuoStrength fan!

**Comment by Keith12345678910** [comment]
I'm having the same issue. Once the menu moved to the left, now the extension doesn't work. Nothing appears. Also tried reloading it and still same issue.

**Comment by ToranSharma** [comment]
@Ajakab98, @Keith12345678910,
Thanks for reporting, I'll take a look at this today and get a fix as a soon as I can.

Toran

**Comment by alexseyk** [comment]
FYI 

another version of the re-design ... no sections ... no crowns :( 

<img width="1301" alt="Screen Shot 2022-10-16 at 20 59 17" src="https://user-images.githubusercontent.com/60418150/196039572-abcaad1f-5153-4c9c-b239-e4b58ba1ecd4.png">

https://blog.duolingo.com/new-duolingo-home-screen-design/

**Comment by ToranSharma** [comment]
@alexseyk, Interesting...

Thanks for letting me know. I'm not sure what the future of Duo Strength will look like with this new home screen.

**Comment by ToranSharma** [comment]
@Ajakab98 @Keith12345678910,

I have just published v2.0.31 which should hopefully fix most of the core features.

**Comment by Ajakab98** [comment]
> @Ajakab98 @Keith12345678910,
> 
> I have just published v2.0.31 which should hopefully fix most of the core features.

Hello Toran,

Thank you for publishing the latest version, the DuoStrength features are working once again on my version of the desktop Duolingo site!
