### ISSUE TITLE
UI Issue was closed by the original OP yesterday, but I'm reopening it because the version in the Chrome Store is outdated

### ISSUE THREAD

**Issue by Keith12345678910** [ToranSharma/Duo-Strength#224]
Hi there, I see the issue related to the UI was fixed and you wrote it was published yesterday, but on the Chrome Web Store it still shows the last version on Sept 27th. I was concerned because the original OP said it was fixed (as did you), but I don't see how to get the latest version for Chrome. Is there a delay from the time that you publish to the point that we would see the updated version?

**Comment by ToranSharma** [comment]
@Keith12345678910,

Sorry I should have said in my comment on #222 that the update was still pending approval on the chrome store. This normally takes just a couple of hours, but can take longer. I think the weekend probably slowed it down a little.

I can see now that it is *still* in pending approval. I'll update here when this changes.

Also note that the Firefox and Opera approval times are typically much fast, in the order a few minutes normally. The previous OP was likely using Firefox and had the update already.

**Comment by ToranSharma** [comment]
Here is how the Chrome dashboard looks on my side, note the `Pending review` status in the top left.
![Screenshot 2022-10-17 at 18 44 16](https://user-images.githubusercontent.com/4559968/196246434-cd15b63a-3551-4efe-b43b-3de0ca1ff59c.png)
