### ISSUE TITLE
Future of Duo-Strength  - add old  UI site 

### ISSUE THREAD

**Issue by alexseyk** [ToranSharma/Duo-Strength#225]
Hi Toran 

Since  Duo-Strength  does not work with the new UI 
Please  add https://www-internal.duolingo.com/learn to the list of sites

**Comment by ToranSharma** [comment]
@alexseyk Thanks for bringing this to my attention, I'll add this now and get a release out as soon as I can: v2.1.0

**Comment by ToranSharma** [comment]
Published [v2.1.0](https://github.com/ToranSharma/Duo-Strength/releases/tag/v2.1.0) to all the stores. Approved for Opera, pending review for Chrome and Firefox.

**Comment by ToranSharma** [comment]
Firefox now approved.

**Comment by das-g** [comment]
<https://www-internal.duolingo.com/> now redirects to https://www.duolingo.com/learn. :cry:

Is there any other workaround to still access the old Duolingo interface and thus use this great extension?

**Comment by alexseyk** [comment]
> https://www-internal.duolingo.com/ now redirects to https://www.duolingo.com/learn. 😢
> 
> Is there any other workaround to still access the old Duolingo interface and thus use this great extension?

If you use Firefox.... block https://www.duolingo.com/learn then https://www-internal.duolingo.com/  or https://join.duolingo.com/  will show you the tree. 

(c) https://forum.duome.eu/viewtopic.php?p=41584-escape-the-snake#p41584

<img width="1128" alt="Screen Shot 2023-01-30 at 15 45 00" src="https://user-images.githubusercontent.com/60418150/215434745-e44aaa68-e91a-4997-89c7-b50ac07af0b2.png">
