### ISSUE TITLE
Fully Strengthened Tree Skill Suggestion Option - Unclear Behavior

### ISSUE THREAD

**Issue by alexseyk** [ToranSharma/Duo-Strength#36]
Please consider adding help or information  to user manual as of how 
Fully Strengthened Tree Skill Suggestion - Skill at the Current Crown Level 
Option is supposed to work 
 My tree has skills at L5, L4 & L3. what is Current Crown Level  ?

see image below. clearly tree is NOT fully strengthened 
<img width="666" alt="Screen Shot 2020-01-29 at 17 08 44" src="https://user-images.githubusercontent.com/60418150/73347439-2a584680-42ba-11ea-9950-045b7b3a037c.png">
 and with Needs Strengthening Option enabled 
<img width="677" alt="Screen Shot 2020-01-29 at 17 10 40" src="https://user-images.githubusercontent.com/60418150/73347512-4e1b8c80-42ba-11ea-9dec-87c2a65d0f14.png">

Please add filter (5 check box options) to select Level of the skills that need strengthening : for example  if i want to focus on skills at L3 only and ignore skills at other Levels

**Comment by ToranSharma** [comment]
Hi @alexseyk,

The definition of the Crown Level of a tree is taken from duome.eu. It is simply defined as the minimum crown level of all the skills in the tree. For example, in your case if you only have skills at crown level 3, 4 & 5, the crown level is 3. If the tree is unfinished, it is at level 0 as there are some skills that are unfinished, and are therefore at level 0 still. Note that bonus skills are ignored. 

I could add this definition as a tool tip if you hover over the crown tree level sentence in the crowns info pop up box. Given that this statistic is a direct mirror of the duome behaviour, I did not at the time of making it see the need to explain its meaning, as it is not explain on duome either.

Regarding the screen shots you sent, the wording of the skill suggestion, and perhaps even when it is displayed, need to be changed to take into account if there are skills that need to be strengthened. Currently, if you disable the Needs Strengthening List option, it supposes that you are not interested in strengthening any of the skills that are not at 100% strength. At this point the information is passed on that are no skills that the user is interested in being strengthened, so the skills suggestion is added.

The skills suggestion selects, by default randomly, a skill from the lowest crown level and suggests that the user do a lesson on this skill to contribute toward getting the tree up to the next level. For example in your case, as described above the minimum crown level of all your skills is 3, so your tree is at level 3. Doing lessons on these level 3 skills will eventually get them all up to level 4, thus making your tree at crown level 4 overall. This is why the sentence is worded as, "Why not practice this skill to work towards getting you tree to Level 4".

I believe what you are requesting is that if you have, say 26 skills that need strengthening some of them at level 3 and some at level 4, that you want to prioritise strengthening the level 3 skills first. If this is what you want then I can add a sorting option for the needs strengthening list to sort by crown level.

This is probably how it should have been by default already, so I would now make this the default sorting option for new users. I am not sure if I want to force the change on current users, even if I think it is a better method.

I hope this clarifies some of you questions, and the proposed new sorting method solves your problem,

Toran

**Comment by alexseyk** [comment]
Toran
I understand the duome definition of Crown Level, I think they mainly refer to it as Tree Level. 
And in crowns you clearly state what the tree Level is.

Consider changing the wording in the options
 "Skill at the Current Crown Level"  to "Skill at the **Lowest** Crown Level"  or  "Skill at the Current  **Tree** Level"

Thanks for explaining the logic behind Fully Strengthened Tree Skill Suggestion. It was unexpected that it ignores un-strengthened skills if the option Needs Strengthening List is disabled.
Given such behavior you might want to rename option name es well  

Yes you are correct with multiple skills that need strengthening i would want to focus on those with lowest level. 
I was asking for  "filter by skill level"  option because i don't know if you can do 2 columns  sorting like in Excel. 1st by  level and 2nd  by reverse tree for example
Thanks
Alex

**Comment by ToranSharma** [comment]
Hi again Alex,

Yeah I can see how the wording of that option isn't clear, I will change it to "Current **Tree** Level". This has been done in 899133c.

It currently, doesn't make much sense the way the skill suggestion is displayed if you bypass the needs strengthening list. I will rename the skill suggestion option to remove mention of fully strengthened and add a sub option to toggle if the skill suggestion should be displayed when there are skills that need strengthening.

Multi-pass sorting for the needs strengthening list shouldn't be too hard to implement, though I am not sure exactly how I will let the user choose this in the options yet.

Thanks,

Toran

**Comment by ToranSharma** [comment]
The skill suggestion changes have been made in ce153db.

**Comment by alexseyk** [comment]
Great !
about Multi-pass sorting: 
I am all for giving user more options but for practical purposes just hard coding **reverse sorting by skill level** on top of existing sorting options  should be a quick fix. i think.

**Comment by alexseyk** [comment]
on the other hand skills can be at 25, 50 & 75% strength, so it's a third pass for sorting. 
just something more to consider.

**Comment by ToranSharma** [comment]
Hi again,

Been working on the multi criteria sorting of the needs strengthening list, it was more work that I thought it would be to get the options page how I wanted it.

The sorting option is now multi part. The first drop down contains four new options, for sorting by strength and crown level, in both ascending and descending order.
![Sorting Method Dropdown 1](https://toransharma.com/i/Sorting%20Method%20Dropdown%201.png)

If any of those last four are selected, there is a link to add another sub criterion.
![Sorting Method Options](https://toransharma.com/i/Sorting%20Method%20Options.png)

These further criteria have the invalid methods removed.
![Sorting Method Dropdown 2](https://toransharma.com/i/Sorting%20Method%20Dropdown%202.png)

There are up to three levels of sorting available, as all possible tertiary sorting criteria leave no ambiguity in the order. Secondary and tertiary criteria have a remove button that will remove that criterion and any further criteria.

![Three Sorting Criteria](https://toransharma.com/i/Three%20Sorting%20Criteria.png)

It is a little harder to show a screenshot of the sorting in action, but I have checked its functionality in Chrome, Firefox and Opera and all seem to sort things as per the criteria in the options.

Currently, the default method is still Tree Order. This can be changed, but as it will only affect new installs, I think I will leave it as is.

These changes have been made in 3450245.

I hope this fulfils what you had in mind,

Toran

**Comment by ToranSharma** [comment]
I have merged the issue branch in to develop in abf7782.
