### ISSUE TITLE
UI: additional icons (info) for languages 

### ISSUE THREAD

**Issue by alexseyk** [ToranSharma/Duo-Strength#37]
Hi Toran
On the forum over the years there were multiple suggestion to have somewhat different icons (flags) for the completed language trees and / or to show progress 
https://forum.duolingo.com/comment/8335323
 https://forum.duolingo.com/comment/9896339
https://forum.duolingo.com/comment/12853199
https://forum.duolingo.com/comment/4891839
<img width="296" alt="Screen Shot 2020-01-30 at 10 39 00" src="https://user-images.githubusercontent.com/60418150/73418471-2aa22180-434e-11ea-88b0-1295927115d5.png">
See if you can implement something like that or add info similar to what is at duome now
<img width="456" alt="Screen Shot 2020-01-30 at 10 39 15" src="https://user-images.githubusercontent.com/60418150/73418508-58876600-434e-11ea-879a-ad077364470d.png">
all this info can be an overkill but a small icon (owl?)  next to the the flag will be really cool 
<img width="204" alt="Screen Shot 2020-01-30 at 10 39 25" src="https://user-images.githubusercontent.com/60418150/73418592-b87e0c80-434e-11ea-8297-bc6ef517fd2d.png">
<img width="657" alt="Screen Shot 2020-01-30 at 10 55 27" src="https://user-images.githubusercontent.com/60418150/73418692-0f83e180-434f-11ea-9a53-0944eebac4d3.png">

**Comment by ToranSharma** [comment]
Hi,

How does this look?

![image](https://user-images.githubusercontent.com/4559968/76781307-6d0caa00-67a6-11ea-8303-c5016cbfadbd.png)

It uses the same colours as duome, which are the background colours on duolingo for skills of that level. While duome distinguishes unfinished trees by having the icon greyed out, I do not want to do this as it might be confusing, as such, unfinished trees have a white border, and L1 Trees blue (as per the duolingo skill colours).

There is no indication for a fully strengthened (golden) L5 tree as the the information used to for all trees other than the currently active one are cached and so may not reflect changes. Note that this is true for duome as well; there is no way (that I know of) to check the strengths of a tree that isn't the one currently selected.

Note that all trees default to white (L0) until they have been switched to at least once. This is unfortunately as a result of the above, and Duo Strength's progress storage method, which until now did not distinguish trees by the language they are being learned from. For example, en->es and ru->es were treated as the same by Duo Strength, so the data saved about the trees would overwrite each other. This has now been changed and they are stored individually.

**Comment by alexseyk** [comment]
Hi Toran
Did your test the color borders for trees with different base languages?
I am not overly concerned about not showing L0 trees or not fully strengthen ones, since duolingo does not provide any indication on the flags - anything is an improvement. 
As L4 & L5 colors are too similar to distinguish easily would it be possible display  a crown (in addition to or instead of the color border) for L5  tree  or change the border thickness
<img width="311" alt="Screen Shot 2020-03-17 at 04 48 50" src="https://user-images.githubusercontent.com/60418150/76802606-9eb75c80-680a-11ea-970a-84402cbb8117.png">
 ?
Thanks

**Comment by ToranSharma** [comment]
> Did your test the color borders for trees with different base languages?

Yes, as said above I had to change how to crowns progress for each language is stored so that the same target language from different base languages are stored separately. 

I will have a look at adding a small crown logo in the corner of L5 flags or something else to distinguish them more.

**Comment by ToranSharma** [comment]
Here is a comparison of the alternatives you suggest.

Current:
![No change to L5](https://user-images.githubusercontent.com/4559968/77082258-b998f500-69f3-11ea-904e-70d9f7aaae83.png)

Alternatives:
![Crown icon on L5 Tree](https://user-images.githubusercontent.com/4559968/77082062-79d20d80-69f3-11ea-9859-7926d77cf43a.png) ![Thicker L5 gold border](https://user-images.githubusercontent.com/4559968/77081899-3a0b2600-69f3-11ea-94b1-0404f3277291.png)

Personally I don't think that it is too hard to differentiate between the gold and orange borders of L5 & L4 trees as is, but that will change based on the screen being used. What do you think?

**Comment by alexseyk** [comment]
I like the one with the **crown**. The thick border looks too ugly. While it may not be too difficult to distinguish gold & orange colors, it is harder to remember which color corresponds to which level. And crown clearly announce L5 course completion :) 
My early question about testing borders was because i was not sure how the border will work/look : i thought it might include base & target language flags

**Comment by ToranSharma** [comment]
The crown version has been added in 19a7242

**Comment by ToranSharma** [comment]
The flag borders changes have been added in db9e162
