### ISSUE TITLE
suggestion : play audio keyboard shortcut 

### ISSUE THREAD

**Issue by alexseyk** [ToranSharma/Duo-Strength#38]
to save on mouse clicks and movement please add (if possible) a shortcuts  to replay audio.  
Some sentences are too long to remember and in others some words have poor pronunciation, so i keep re-playing those audios
for example Left Shift for normal speed and Right Shift for slow playback 
Thanks
<img width="307" alt="Screen Shot 2020-01-31 at 17 00 20" src="https://user-images.githubusercontent.com/60418150/73532178-c0bd7100-444e-11ea-80a7-11f35f9b31ec.png">
<img width="673" alt="Screen Shot 2020-01-31 at 16 58 58" src="https://user-images.githubusercontent.com/60418150/73532187-c450f800-444e-11ea-9167-605db9815274.png">

**Comment by ToranSharma** [comment]
There are already Duolingo hotkeys for this. Ctrl+SPACE for normal speed, and Ctrl+Shift+Space for slow.

The only drawback of these is that Ctrl+Space is a hotkey in Opera for something already, but if you are using another browser, that should be fine. I use them every lesson. The normal speed hotkey works on any question with a speaker icon, even stories I believe.

Hope that helps,

Toran

**Comment by alexseyk** [comment]
Thank you!  How about a shortcut for a microphone icon ?

**Comment by ToranSharma** [comment]
If you mean to start the recording for a speaking question, then ENTER does that.
