### ISSUE TITLE
Suggestion: add  links to re-do checkpoints and "test out" skills

### ISSUE THREAD

**Issue by alexseyk** [ToranSharma/Duo-Strength#39]
as i describe on the forum 
https://forum.duolingo.com/comment/36331804
can you add those links to the "towers" ?
https://www.duolingo.com/checkpoint/Language/Number
https://www.duolingo.com/bigtest/Language/Number

**Comment by ToranSharma** [comment]
Currently, the skill suggestion will provide a link to the next checkpoint if that is the next this to do, i.e. all skills up to the check point have been finished.

Where and when would you want the links to these be displayed?

**Comment by alexseyk** [comment]
I  am thinking more in the context of re-doing & re-passing i.e. sort of like practice. Like in the  issue #35 you've added PRACTICE button so add 2 buttons to the "towers", after the checkpoints were passed.   
<img width="298" alt="Screen Shot 2020-02-17 at 19 42 30" src="https://user-images.githubusercontent.com/60418150/74655507-0ef8a100-51bf-11ea-8ed3-e85f98d0a35c.png">

I am not sure how to name those 2 buttons. "Try checkpoint challenge " &  "Test out all skills above"  . Something shorter would be better.

**Comment by ToranSharma** [comment]
I see, sorry I think I didn't quite realise what you meant. Yes that should be doable. I'll look into doing something similar to the practice button in issue #35.

**Comment by ToranSharma** [comment]
How does this look?

![Additional Checkpoint Buttons](https://user-images.githubusercontent.com/4559968/75467374-706cfc80-5983-11ea-8f4f-b6a19c961852.png)

The first button takes you to the checkpoint, the second to the 'bigtest'.

**Comment by alexseyk** [comment]
may be name 2nd "retry above skills" ? 
i think we need to add "retry" to both or drop altogether, hoping it will be understood 
or name 2nd " Test skills to Level 1" 
i am really not sure what's the best way to name it :(

**Comment by ToranSharma** [comment]
What is the behaviour when you do a big test for a checkpoint you have already reached? Does it not do anything towards getting the skills in that section up to the next Crown Level? I think I had assumed say, all the skills were at least L1, that it would make them all to at least L2.

If that is not the case then yes I will rename it to something else.

**Comment by alexseyk** [comment]
No. it raises skills only to L1. 
Duo allows to do big test only when there are skill at L0 above, but 
one row or so, before reaching the tower it grays-out  and Duo locks-out  challenge & bigtest 
upon completing remanning skills it un-locks the tower for the challenge.
Opportunity to do big test is lost. 
It is like placement test. You can do it only once, except 
Via direct links both bigtest and challenge are accessible anytime.
All they do is provide Level 1 practice. At least it is how I view & use them.
It seems to be no difference in type of questions for big test if all or any of the skills are at L0 or L1 

XP from challenge & biggest **sometimes** is NOT counted towards daily goal & leaderboard. however it is reflected in total XP

**Comment by ToranSharma** [comment]
I see, I think I had assumed it would be like testing out all the skills to the next level each time.

I'll change it to something that closer reflects it's function.

**Comment by ToranSharma** [comment]
![image](https://user-images.githubusercontent.com/4559968/75570848-ef2f6b80-5a4f-11ea-9034-090171849343.png)

I think I'll go with this, while not as succinct as it was before, I think it is clearer now. You will still be presented with the start screen that gives more information once you click the button.

Added in ced3646
