### ISSUE TITLE
suggestion: links to forum from lesson review

### ISSUE THREAD

**Issue by alexseyk** [ToranSharma/Duo-Strength#40]
would it be possible to add links to the corresponding forum sentences  discussion  from the lesson review ?
<img width="840" alt="Screen Shot 2020-02-08 at 10 41 13" src="https://user-images.githubusercontent.com/60418150/74078695-0508cc80-4a60-11ea-8e63-72f7a8ecbb8f.png">

**Comment by ToranSharma** [comment]
Hi again Alex,

I have had bit of a think about this one and I think it is probably possible, but I am not sure exactly how I would approach it. From what I have seen thus far, the text for the link isn't anywhere in the page, so I would have to grab it from somewhere else, either the duolingo code or from network activity.

I think that I will leave this until after I have released v1.3 with all the other new features you requested, then I can look into it more closely. Currently it will delay even further the release of the other things I have worked on for v1.3, which I had thought I would release over a month ago.

Toran

**Comment by alexseyk** [comment]
Sure, especially since the extension stopped working after yesterdays website re-design

**Comment by alexseyk** [comment]
duoStrength.js:68 Uncaught (in promise) Error: Extension context invalidated.
    at duoStrength.js:68
    at new Promise (<anonymous>)
    at retrieveOptions (duoStrength.js:66)
    at init (duoStrength.js:2696)
    at MutationObserver.childListMutationHandle (duoStrength.js:2435)

**Comment by ToranSharma** [comment]
What version are you on? #55 was causing that error on trees with bonus skills. I released v1.2.11 to fix that.

**Comment by alexseyk** [comment]
it must have been one of the previous versions . I have v1.2.11 now   and issue is resolved.

**Comment by ToranSharma** [comment]
Having been shown [Duolingo Solution Viewer](https://github.com/blmage/duolingo-solution-viewer), and looking at how it works, I now can see a way of accessing the discussion ID for each sentence from the sessions file that is requested at the start of a lesson. Hopefully I can use this to generate a url to the discussion page for each sentence, which could then be added to the review screen.
