### ISSUE TITLE
Suggestion : add % to the crowns 

### ISSUE THREAD

**Issue by alexseyk** [ToranSharma/Duo-Strength#41]
Suggestion : add % to the crowns same way as % xp to next level.  This will give an indication for tree (course) completion
<img width="414" alt="Screen Shot 2020-02-18 at 12 58 12" src="https://user-images.githubusercontent.com/60418150/74708342-c38dd380-524e-11ea-890b-b8eea77d83d9.png">

**Comment by ToranSharma** [comment]
Is this the sort of thing you had in mind?

![Crowns Breakdown with Percentages](https://user-images.githubusercontent.com/4559968/75242115-60a4bb00-57bf-11ea-857a-a7bb8b9311ff.png)

I have not bothered for the bonus skills as it would be fairly pointless, note that they are not included in to percentage calculation for normal skills either.

**Comment by alexseyk** [comment]
Sorry my request  was not clear. I meant % in total count, not in individual break down.  This is too much info :).

In the crown itself

 249 / 320 
  77.8%

**Comment by ToranSharma** [comment]
Ah I see. Putting the overall crown percentage shouldn't be too hard, just need to find a good place to put it. I'll have a play around and see.

**Comment by ToranSharma** [comment]
Is this more like it?
![image](https://user-images.githubusercontent.com/4559968/75265874-6b744580-57e9-11ea-8fe9-2c29c51f92b0.png)

**Comment by alexseyk** [comment]
yes ! you are the best !

**Comment by ToranSharma** [comment]
This has been added in 638ccd8.
