### ISSUE TITLE
Bug? strength bar not shown for En<>Es trees 

### ISSUE THREAD

**Issue by alexseyk** [ToranSharma/Duo-Strength#42]
For whatever reason strength bar and XP info are not shown for  En<>Es trees , as well as Lists ( cracked, strengthening) 

<img width="1269" alt="Screen Shot 2020-02-18 at 13 10 36" src="https://user-images.githubusercontent.com/60418150/74708905-6561f000-5250-11ea-987a-9a645b2ff276.png">

disabling strength bar  will show previously missing data 

<img width="1188" alt="Screen Shot 2020-02-18 at 13 12 24" src="https://user-images.githubusercontent.com/60418150/74708885-57ac6a80-5250-11ea-8974-622a312ee4cc.png">

This behavior does not affect other trees that i have

**Comment by ToranSharma** [comment]
Hmm, that is a strange one that it is affecting only one tree. Do you see any errors in the browser console. You can bring this up by right clicking somewhere on the web page, then selecting inspect at the bottom.

![Inspect context menu item](https://toransharma.com/i/inspect%20context%20menu%20item.png)

Then in the window that appears there will be a console tab at the top.
![Console Tab](https://toransharma.com/i/console%20tab.png)

Errors will appear in red in that window. The source of the error is on the right, and will say duoStrength.js if it is from Duo Strength.


Based on what you have shown, it seems like there is likely an error in the part of the code that is run to add the strength bars, and so if that option is disabled, it isn't run so no error.

**Comment by alexseyk** [comment]
Yes there are errors 
[www.duolingo.com-1582028597186.log](https://github.com/ToranSharma/Duo-Strength/files/4219192/www.duolingo.com-1582028597186.log)
[www.duolingo.com-1582028987275.log](https://github.com/ToranSharma/Duo-Strength/files/4219193/www.duolingo.com-1582028987275.log)
here are couple logs

**Comment by ToranSharma** [comment]
Thanks, i'll look into it. Duolingo slightly changed the page structure over the last day or so. I think this is causing some problems.

**Comment by ToranSharma** [comment]
From some issues I am seeing, it seems to be a problem detecting which skills in the tree are bonus skill. Any bonus skills are being thought of as normal skills, this is causing it to think there are more skills than I have strength values for and a list is going out of bounds.

**Comment by ToranSharma** [comment]
Going to fix this and strength bar styling change in a hotfix branch and will release it as v1.2.3

**Comment by alexseyk** [comment]
PS:  it also shows XP info in the steak drop down window not in the XP progress block.
Yes, of all the courses i have only those 2 have bonus skills .
Duome have strength info for bonus skills. 
So far i have not seen bonus skills crack.
Personally i am waiting for v1.3 with all  nice new features :) 

<img width="497" alt="Screen Shot 2020-02-18 at 20 12 46" src="https://user-images.githubusercontent.com/60418150/74740094-cad3d200-528c-11ea-87ab-c9f18e718f17.png">

**Comment by ToranSharma** [comment]
I have fixed the strength bar issue now in 4126a2c.

The XP info ending up in the streak is an interesting one. I can only get it to happen if I am already hovering over the flame icon while the page is loading. This is a carry over from when it was originally put there in v1.1.0. I'll see if I can stop that from happening.

**Comment by ToranSharma** [comment]
Fixed that now too as of 220e8bd.

I'll package up these changes and push them out as v1.2.3.

Sorry you'll have to wait for v1.3 a little longer while I finish up on the features going into that.
