### ISSUE TITLE
Page focus & Strength bar 

### ISSUE THREAD

**Issue by alexseyk** [ToranSharma/Duo-Strength#47]
with **disabled** strength bar page stays focused on the last lesson completed 
<img width="497" alt="Screen Shot 2020-02-25 at 11 36 07" src="https://user-images.githubusercontent.com/60418150/75215363-086fb800-57c3-11ea-97c8-9aade927e75e.png">

with **enabled** strength bar page focus shifts
<img width="655" alt="Screen Shot 2020-02-25 at 11 31 56" src="https://user-images.githubusercontent.com/60418150/75215404-2ccb9480-57c3-11ea-8e1f-e4879982b418.png">

it is uncomfortable to scroll down to the lesson in question every time 

PS. I've seen skills crack at lower levels too. You may want to add sorting by crown level in the cracked list option.

**Comment by ToranSharma** [comment]
I'll see if I can work out a way of keeping a similar view after the page gets longer from the strength bars.

Regarding the cracked skills, I didn't think it was possible for a skill that isn't at Crown 5 to crack. From Duolingos own "Gold Skills and Spaced Repetition" post:

> When our spaced repetition algorithm deems it’s time to review concepts taught in a skill, the skill will turn from Level 5 gilded to a Level 5 cracked skill.

If you send a screenshot of a non L5 skill cracking I'll look into it and add multi level sorting options like for the needs strengthening list.

**Comment by alexseyk** [comment]
Toran
make them vertical and call them "weak pole" :)
to keep focus, i think there is a way to rememberer amount of page scrolling prior to page reload 
imho - vertical is better - less page scrolling - you can make it like a rising temperature gauge in original  colors

I was surprised to see  L1 (in uk<?>en)  and L3 & L4 ( in ru>es) cracked skills too, especially since they turned to gold. they got back to original color after practice. 
May be it's an A/B test. I'll make sure to make screenshots for you

**Comment by alexseyk** [comment]
<img width="757" alt="Screen Shot 2020-02-26 at 19 50 05" src="https://user-images.githubusercontent.com/60418150/75347096-a2725600-58d2-11ea-8aff-ff02399dc1c1.png">

**Comment by alexseyk** [comment]
![Untitled](https://user-images.githubusercontent.com/60418150/75427810-c2108980-5979-11ea-96da-844b044c6093.png)

**Comment by alexseyk** [comment]
![Untitled](https://user-images.githubusercontent.com/60418150/75428187-5bd83680-597a-11ea-8a23-0c4c10ea64a6.png)

**Comment by ToranSharma** [comment]
Hmm it does seem like a new change that they are testing. The fact that they turn gold when cracked is very strange, and feels like they haven't finished developing the feature. I think I'll hold off making any changes to accommodate it until it is implemented properly for everyone.

**Comment by ToranSharma** [comment]
I have just implemented a fairly simple fix for the scrolling issue. When the extension loads, it checks for a popout box for a skill, if there is one, it scrolls it into view. After the rest of the loading of all the other features, it is then scrolled into view once more.

The box is also scrolled into view when a practise button is added to a skill popout, as the box gets larger so the bottom can be cut off.

These changes were made in 94cd9a9.
