### ISSUE TITLE
Strength bar not shown with duolingonextlesson script 

### ISSUE THREAD

**Issue by alexseyk** [ToranSharma/Duo-Strength#48]
Strength bar not shown with duolingonextlesson script 
https://github.com/camiloaa/duolingonextlesson

[www.duolingo.com-1582819295197.log](https://github.com/ToranSharma/Duo-Strength/files/4262546/www.duolingo.com-1582819295197.log)

**Comment by alexseyk** [comment]
FYI: this strength bar viewer script works with the  duolingonextlesson script

 https://github.com/x-inkfish-x/DuolingoUserscripts/wiki/Userscript:-Strength-Viewer

**Comment by ToranSharma** [comment]
Hi,

Just looked into this and made a straight forward fix. The issue was that the added skill at the top of the tree was being treated as a real skill in the tree to add a strength bar too. This led to there being more skills than we had strengths for.

Fixed in 759d6b9.
