### ISSUE TITLE
Strength bars not showing in EN>ES tree due to change in bonus skills id

### ISSUE THREAD

**Issue by milankostak** [ToranSharma/Duo-Strength#55]
Hi. Thank you for the update from yesterday. However, it seems that there still some problems. In my EN>ES tree, I don't see the strength bars. I did some digging, and it seems that it is (again) connected to a change of the ID of bonus skills.
This line fixed the problem for me: `const BONUS_SKILL_DIVIDER = "_23P6X";`

Duo-Strength version: 1.2.10
Browser: Vivaldi (basically Chrome)

This is the full log from the console:

duoStrength.js:711 Uncaught (in promise) TypeError: Cannot read property '0' of undefined
    at addStrengths (duoStrength.js:711)
    at getStrengths (duoStrength.js:2020)
    at handleDataResponse (duoStrength.js:2205)
    at duoStrength.js:2235
    at requestResponseMutationHandle (duoStrength.js:2133)
    at MutationObserver.requestResponseHelper (duoStrength.js:2092)

**Comment by ToranSharma** [comment]
Hi thanks for reporting this.

I must have forgotten to check if the bonus skill divider class changed. I desperately need to write a checklist to go through to check all the different features...

I'll make the change and do some more testing then release it as v1.2.11.

Toran

**Comment by ToranSharma** [comment]
The classname for the bonus skill dividers has been updated in d7ea1e41a4e6b96cdaaa766afea135f726c04fb0. I am about to package up and release v1.2.11 including this change.

**Comment by ToranSharma** [comment]
v1.2.11 has now been released on all browsers.

Thanks again for letting me know about the issue!

Toran
