### ISSUE TITLE
Fully Strengthened Tree Skill Suggestion

### ISSUE THREAD

**Issue by alexseyk** [ToranSharma/Duo-Strength#59]
May I suggest you change the text 
"All the skills that you have learnt so far are fully strengthened. The next skill to learn is: Descriptions 2"
 to start 2nd sentence from the next line : i.e.
 "All the skills that you have learnt so far are fully strengthened. 
The next skill to learn is: Descriptions 2"

If anyone  uses https://github.com/camiloaa/duolingotreeenhancer the message  is not displayed properly 
<img width="1149" alt="Screen Shot 2020-04-12 at 08 13 44" src="https://user-images.githubusercontent.com/60418150/79058242-8e719080-7c95-11ea-96d2-353a59368a60.png">

The other messages at least are displayed OK... Inside the DuolingoTreeEnhancer , but ok :) 
<img width="705" alt="Screen Shot 2020-04-12 at 08 15 10" src="https://user-images.githubusercontent.com/60418150/79058267-f1632780-7c95-11ea-8fac-e0b2bef7de07.png">

**Comment by ToranSharma** [comment]
I can put the new line there. However, if you have no cracked skills as well the message is currently:

All the skills that you have learnt so far are fully strengthened, and none are cracked. The next skill to learn is: SKILL

So the new line would only make sense after the full stop, in which case, the sentence would still be too long.

I don't have any experience with this userscript, I might try and load it up to see why the sentence is overflowing. If I can get the text to wrap normally that would be the best solution.

One thing I don't quite understand is what the enhanced tree box is for, you seem to be suggesting that the suggestions shouldn't go inside it.

**Comment by ToranSharma** [comment]
Just installed it, I understand now, it is button. I think there should be a fairly easy fix to just put the info below this button.

**Comment by ToranSharma** [comment]
Here is how it looks putting the info back in the right place.

![image](https://user-images.githubusercontent.com/4559968/79071646-c9df7f80-7cd4-11ea-8e39-487b75038b18.png)
----------------
![image](https://user-images.githubusercontent.com/4559968/79071882-e62fec00-7cd5-11ea-97d7-854ed83199df.png)

**Comment by ToranSharma** [comment]
These changes have been made in 56e575d. This also includes a better way of accounting for the TRY PLUS button across different languages, where the button may had different widths.
