### ISSUE TITLE
Focus change in V1.3.3 :( 

### ISSUE THREAD

**Issue by alexseyk** [ToranSharma/Duo-Strength#63]
After i finish a lesson or practise of a skill the focus is changed to the top of the tree :(  Please keep it on the current skill. 
Thanks

PS option "Focus First Skill in Lists" was  disabled 

The issue is NOT happening when strength bars are enabled :)

**Comment by ToranSharma** [comment]
How are you entering the lesson for that skill, from one of the lists or buy scrolling through the tree and manually clicking on the skill?

From my testing if a skills popout bubble is displayed when the tree is loaded after exiting a lesson, the skill popout will be centred on the screen, regardless of if the "Focus First Skill in Lists" option is enabled or not.

**Comment by alexseyk** [comment]
by scrolling through the tree and manually clicking on the skill. It affects **practise** button 

it makes no difference if 
Needs Strengthening List & Cracked Skills List were disabled or enabled .

**Comment by ToranSharma** [comment]
I am still not quite understanding your issue. Everything I can test here, and looking at how the code should run means that the page should not scroll back up to the top if there is a skill's popout is displayed. Instead it should scroll so that it is centred in the middle of the window.

Would be bale to give a step by step guide to reproduce the undesired behaviour, and a description of what you think it should do compared to what currently happens.

Thanks,

Toran

**Comment by alexseyk** [comment]
I understand it is hard to troubleshoot the issue when you can not reproduce it :(
Step 1 start practise 
<img width="586" alt="Screen Shot 2020-04-18 at 10 10 17" src="https://user-images.githubusercontent.com/60418150/79626880-093b1f80-815e-11ea-9fc9-cec522701ba4.png">
Step 2 after lesson is finished it is scrolled to the top of the tree :( 
<img width="471" alt="Screen Shot 2020-04-18 at 10 15 30" src="https://user-images.githubusercontent.com/60418150/79626890-28d24800-815e-11ea-96b8-0610421f77da.png">
I have the following settings 
<img width="396" alt="Screen Shot 2020-04-18 at 10 21 05" src="https://user-images.githubusercontent.com/60418150/79626921-5d460400-815e-11ea-874d-4cdca582fc91.png">
<img width="379" alt="Screen Shot 2020-04-18 at 10 21 14" src="https://user-images.githubusercontent.com/60418150/79626924-6040f480-815e-11ea-99b9-a584103a949b.png">

I am using Google Chrome is up to date Version 81.0.4044.113 (Official Build) (64-bit)
with   https://github.com/camiloaa/duolingotreeenhancer & https://github.com/liuch/duolingo-scripts & https://chrome.google.com/webstore/detail/duoleavemealone-for-duoli/clipadhhddnpnocanhnbonnhppdibnpf  on Mac Os 10.14.6.
Chrome is in full screen with zoom 125% 
If that matters...

The "work around" enabling strength bar does not work any more.
Desired behavior if for treen NOT to scroll to the top and stay focused on the last skill  learned / practiced.

**Comment by ToranSharma** [comment]
Ah I understand now. I think I missed that it only is happening when you click on the new practise button.

The current behaviour is as a result of the page's url being change to the practice session. This means that the page is fully reloaded after clicking the button and any page scrolling information is lost. In this way, clicking the practise button has the same behaviour as clicking a link in one of the lists at the top of the tree.

It should be possible to store which skill was clicked on in the browsers storage API. I could then try and use this to locate the skill in the tree and simulate a click on the icon to bring up the skill's popout. If the popout is displayed when the main `addFeatures` function of the extension is run, the page should scroll this into the middle of the display.

I will start testing to see how viable this solution is.

**Comment by ToranSharma** [comment]
I have implemented the above change in 385c8af.

This is now the behaviour:

Scroll down to a skill.
![image](https://user-images.githubusercontent.com/4559968/79643978-c600a100-819d-11ea-97ba-56cc11d70c21.png)

Click the **PRACTISE** button to enter the practice session.
![image](https://user-images.githubusercontent.com/4559968/79644013-111ab400-819e-11ea-9af2-2b605476785c.png)

The session in then finished (or exited), and this is the view:
![image](https://user-images.githubusercontent.com/4559968/79644062-6656c580-819e-11ea-9153-96b6fbc6c3f1.png)

Which should be exactly what was seen before entering the practice.

Note that this behaviour should be the case for any set of options that has the **PRACTISE** button enabled.

**Comment by alexseyk** [comment]
Thank you ! Does this fix apply to checkpoints and bigtests ?

**Comment by ToranSharma** [comment]
Unfortunately not, it only occurred to me after I had released v1.3.5 that I could do a similar thing with the checkpoint popouts. I'll see if I can do something similar

**Comment by ToranSharma** [comment]
I have now added this in 67e5909.
