### ISSUE TITLE
TOP_BAR variable used without definition

### ISSUE THREAD

**Issue by mattfbacon** [ToranSharma/Duo-Strength#73]
I get the error that getElementsByClassName is not defined. So where is this called?
On line 4382 of duoStrength.js:
`let numNavButtons = topBarDiv.getElementsByClassName(NAVIGATION_BUTTON).length;`
So where is `topBarDiv` defined? On line 4378:
`topBarDiv = rootChild.getElementsByClassName(TOP_BAR)[0];`
So where is `TOP_BAR` defined? It is never defined. Same with `NAVIGATION_BUTTON`, but that error doesn't occur because the previous error halts execution.     
This breaks the extension.

**Comment by ToranSharma** [comment]
Thanks for reporting this.

This sort of thing is a common occurrence, it happens when duolingo makes changes to their code and the class names of various elements get changed. I am working on a fix now to be released in v1.3.10.

As a note, TOP_BAR is defined at the top of the file, as a global constant. Line 36ish
```javascript
const ACTIVE_TAB = "_2lkuX";
const TOP_BAR = "_3F_8q";
const NAVIGATION_BUTTON = "_3MT82";
const QUESTION_CONTAINER = "_2NEKS";
```

**Comment by ToranSharma** [comment]
The class name for TOP_BAR had been changed to "_1frzL". 
The class name for NAVIGATION_BUTTON had been changed to "_1hmv9".

The updated values stop topBarDiv being undefined.

These changes have been made in af1037b

**Comment by ToranSharma** [comment]
These changes have been pushed out in v1.3.10.

**Comment by mattfbacon** [comment]
Sorry, I must have missed those definitions. Anyway, thanks for the quick reply and concise explanation.
