### ISSUE TITLE
Crowns in table view  & XP in pop-up view & DND mode suggestions

### ISSUE THREAD

**Issue by alexseyk** [ToranSharma/Duo-Strength#76]
Please consider adding option for alternative displays of information in table & pop-up respectively.

1) For crowns in a table  - when skills are at all 5 crowns + bonus and graph is displayed it is inconvenient to scroll the pop-up. Table view will be more suited.  PS: Now I  come to think this scrolling can be due to over zoom in my browser  

2) For xp in a pop-up under streak (flame) as you did initially. When you are at the middle or bottom of the tree and want to check how much XP you obtained -  it's a bother to scroll up the page to check - a pop-up view will be more suited.  

3) Do Not Disturb mode : Options to hide XP Progress table, Next Achievements table, Friends Table and others

**Comment by ToranSharma** [comment]
Those options have been added in 9fa5a25.

**Comment by alexseyk** [comment]
Disabling crown graph removes crowns break down from the sidebar :( 
<img width="560" alt="Screen Shot 2020-06-11 at 10 14 05" src="https://user-images.githubusercontent.com/60418150/84341007-4ce55f00-abcc-11ea-9c8b-8f8d1cc97135.png">

Issue seem to be limited to en -> es course only. Info disappears after some mouse movement . Possibly after hovering over crown icon on the top. Also Practice and checkpoint test link did not load :( 

OK Not limited. Same behavior for uk -> en tree

 duoStrength.js:716 Uncaught (in promise) ReferenceError: progressRate is not defined
    at daysToNextCrownLevelByCalendar (duoStrength.js:716)
    at duoStrength.js:2642
    at Array.forEach (<anonymous>)
    at displayCrownsBreakdown (duoStrength.js:2315)
    at addFeatures (duoStrength.js:3308)
    at handleDataResponse (duoStrength.js:3638)
4duoStrength.js:716 Uncaught ReferenceError: progressRate is not defined
    at daysToNextCrownLevelByCalendar (duoStrength.js:716)
    at duoStrength.js:2642
    at Array.forEach (<anonymous>)
    at displayCrownsBreakdown (duoStrength.js:2315)
    at MutationObserver.childListMutationHandle (duoStrength.js:4110)

**Comment by ToranSharma** [comment]
The issue seems to be from having the Crowns Info added in both the sidebar and the popup, along with the tree level prediction enabled, while have not enough progress history to use for the prediction so it falling back to using the Calendar. The function to get the prediction from the calendar data has an error, so any code after that is not run. This includes adding the the Crowns Info to the sidebar, which is cleared before trying to update the information.

I get the same error if I freshly add the unpacked extension, and so have no progress history stored. Seems like this is simply a typo on line 716. I had to partially rewrite the prediction functions to add the extra data requested in #77.

Given that the error is coming from the `daysToNextCrownLevelByCalendar` call, I think that this issue will probably only be seen while you have the extension installed by loaded this unpacked source code. I expect that if you switched to the release version it would avoid this by using your stored progress history and the `daysToNextCrownLevel` function instead.

I will patch this up in v1.3.14

**Comment by ToranSharma** [comment]
The errors have been fixed in a2ca484.

All instances of crown level meaning tree level have been fixed in b76cc12.

**Comment by ToranSharma** [comment]
Just been working on the DND mode which I think I will call *Focus Mode*.

There is an option to enable it in the options page, as well as a option to show or hide a button that is show at the bottom of the tree, opposite the global practise button.

![image](https://user-images.githubusercontent.com/4559968/85859262-d42df780-b7b4-11ea-8a11-ee498fff6c04.png)


Here is how it looks at the moment (left- off, right on),

<img width="50%" src="https://user-images.githubusercontent.com/4559968/85858547-b9a74e80-b7b3-11ea-98a6-296b1a099d2b.png" /><img width="50%" src="https://user-images.githubusercontent.com/4559968/85858591-cdeb4b80-b7b3-11ea-9a27-21e028f1097e.png" />

**Comment by ToranSharma** [comment]
I think that the disable focus button looks better being symmetric like this:
![image](https://user-images.githubusercontent.com/4559968/85867041-3fc99200-b7c0-11ea-9aac-a50ee139b485.png)

I have changed this in 97d39a0.

**Comment by ToranSharma** [comment]
I have merged this feature into the develop branch in e7c1069.

**Comment by alexseyk** [comment]
i have v.1.3.24 but focus option & button are not available :( 
using Google Chrome is up to date
Version 83.0.4103.116 (Official Build) (64-bit) on Mac 10.14.16

**Comment by ToranSharma** [comment]
These features have not been published yet, they are in the development branch and will be part of the next release. The next release will be v1.4.0 or v2.0.0 depending on on what else goes into it.

I have been trying to use the [semantic version numbering system: Major.Minor.Fix](https://semver.org/).

It is my desire to only release new features in minor or major releases and not fix releases, though I have not always been constant with this in the especially pre-v1.2.0

I hope that explains the situation. I am not sure exactly when I will release the next feature release, I like to try bundle things together as much as possible to avoid masses of releases and having to write the duolingo forum posts that go with them.

I will be sure to let you know when the next release is out.

**Comment by alexseyk** [comment]
thanks for explaining. I just saw this feature in changelog and thought it was included in the release.
