### ISSUE TITLE
Suggestion: Add language TTL

### ISSUE THREAD

**Issue by avshyz** [ToranSharma/Duo-Strength#77]
I think displaying the info in this dialog (time to complete & course completion percentage)
<img width="300" alt="image" src="https://user-images.githubusercontent.com/3249081/82059014-29fb8400-96ce-11ea-811e-36b97ecc392c.png">
Will be pretty awesome, as it's a huge motivational!
:)

**Comment by ToranSharma** [comment]
Hi,

Much of that information is currently added in the crowns popup window:
![image](https://user-images.githubusercontent.com/4559968/82068207-9d4ec700-96c9-11ea-89df-1b1a38edead1.png)

I could add to this the number of lesson left, and the lesson rate, as given on duome, fairly easily as these values are obviously used in the prediction calculations. I think the reason I have thus far not added them is to avoid cluttering the interface with too much information.

The percentage may be more difficult however, as this requires knowing the total number of lessons per tree level. As it stands, I don't know of a way of calculating this with the information available as there isn't a source of the number of lessons for each skill at each crown level. I believe that duome has this information by having its own database for each tree. This information could be pulled from the thousands of users it tracks, which would give a good coverage of all the trees and their skills at every crown level.

As a note, the prediction calculation Duo Strength uses is not the same as duome once the user has used for extension for more than about 5 days. Once the Duo Strength as enough progress history stored, the predictions should is some sense be more accurate, as it takes into account the things duome notes in that last paragraph about testing out skills or doing lessons on already completed skills to earn more crowns.

I intend to fully document the prediction algorithm I have implemented (and all the other features) in the wiki.

**Comment by avshyz** [comment]
Thanks for the quick reply!
To be honest, when I have requested this feature I wasn't aware it already kinda existed (albeit I now see it's well documented in the README.md, so it's really my fault!)

Now when I look at it I do understand adding that information may be overwhelming. Maybe if you change the table where it shows lessons and the crowns into a bar chart or a pie chart, it might look less cluttered?

Knowing the completion percentage by level is a nice-to-have feature, but it is such a huge hassle it's may not be worth it!

**Comment by ToranSharma** [comment]
A chart in place of the table for the crows information is an interesting idea. I'll have a play around and see what it looks like.

I suppose one other option is add more detailed information in another bubble or tooltip sort of thing when a more information icon is clicked or something like that. Won't be immediately visible, but the information is there to those that are curious.

**Comment by avshyz** [comment]
I think (to have a separate tab for that) this _might_ be a bit of an overkill, given the user can hide either of these pieces of data from the options menu! :)

**Comment by ToranSharma** [comment]
I though I would give the idea I mentioned a try by showing the rate and number of lessons information in a tooltip when hovering over `current rate` in the prediction text.

Here is what it looks like:
![image](https://user-images.githubusercontent.com/4559968/84178021-ae49e880-aa7b-11ea-9a86-a8d590bc5581.png)
Sorry for the compression artefacts, they are a result of using the windows steps recorder to capture the cursor in a screenshot.

I think this is a good way of giving the user that information if they want it while being fairly subtle in the UI.

**Comment by ToranSharma** [comment]
This change is made in 5c5aa5c, and will be released in v1.3.12.

**Comment by avshyz** [comment]
This is incredible! Thanks a lot!! :)
