### ISSUE TITLE
"Show Translation Text" not working

### ISSUE THREAD

**Issue by Pipoderoso** [ToranSharma/Duo-Strength#86]
Text does not hide anymore, not event the button to toggle hide/unhide appears on the screen. 
I have to check/uncheck any option of the Show Translation Text tree for it to work, but then for the next text it stops working again

I have version v1.3.15 and happens on mozilla (77.0.1) and edge (83.0.478.54) in Windows 10

**Comment by ToranSharma** [comment]
Hi, thanks for reporting this issue.

Looks like the Duolingo changed the structure of the lesson page while loaded.

The loading animation at the start is now in its own container and there is main lesson section to observe to see when the lesson is loaded. The now unnecessary checks can be removed and existing observations will cover everything needed.

These changes are made in b3cb39c.

I will push out v1.3.16 with this fix asap.

Toran

**Comment by ToranSharma** [comment]
v1.3.16 has now been released and should be available on Firefox.

Note that Firefox by default only checks for addon updates once a day. You can manually check for updates on the Firefox addons page (about:addons) by clicking on the gear icon and selecting check for updates.
![image](https://user-images.githubusercontent.com/4559968/85573637-fa755b00-b62d-11ea-85d3-32e78b6188bd.png)

**Comment by ToranSharma** [comment]
There were several other related issue that were found after the release of v1.3.16, the latest version is now v1.3.19.
