### ISSUE TITLE
The owl lost its functions ??

### ISSUE THREAD

**Issue by BoKo1** [ToranSharma/Duo-Strength#92]
Was that intended?
I don't see "retry checkpoint challenge"
I don't see "retry crown level 1 test out"
And the owl is so sad :-(

**Comment by ToranSharma** [comment]
Hi @BoKo1,

This isn't intended, Duolingo must have changed something that has broken that feature.

I'll look into it and get a fix out as soon as I can.

Toran

**Comment by ToranSharma** [comment]
I have fixed the issue in 7888ece.

The checkpoint retry buttons are again added to the golden owl trophy message.
![image](https://user-images.githubusercontent.com/4559968/85861135-c2018880-b7b7-11ea-84c1-7f3e858b0ff5.png)

**Comment by ToranSharma** [comment]
I have pushed out the update for Firefox and Opera.

The Chrome Web Store seems to be having some issues at the moment that are preventing developers from uploading updated packages. I will push it out as soon as I can.

**Comment by BoKo1** [comment]
Thanks. A golden owl for you!

**Comment by BoKo1** [comment]
Today I found one more problem. Second option "Retry Crown Level 1 Test out" doesn't work properly.
The website displays the message - ERROR 404

**Comment by ToranSharma** [comment]
Hello again,

Thanks for reporting this. Duolingo seems to have changed the url for the Level 1 Test Outs (aka bigtest). I have fixed this as well as added support for existing practice checkpoint buttons that are being tested currently. Here is what this new button that duolingo is testing looks like:
![Checkpoint Practice Button](https://toransharma.com/i/checkpoint-practice.png).

These changes have been made in fbf7b5d, and will be released in v1.3.23 shortly

Toran
